# renew_before_expiry = 30 days
version = 2.1.0
archive_dir = /home/container/letsencrypt/config/archive/detailing.brandonspg.com
cert = /home/container/letsencrypt/config/live/detailing.brandonspg.com/cert.pem
privkey = /home/container/letsencrypt/config/live/detailing.brandonspg.com/privkey.pem
chain = /home/container/letsencrypt/config/live/detailing.brandonspg.com/chain.pem
fullchain = /home/container/letsencrypt/config/live/detailing.brandonspg.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 0e6d870a17307f84a75ee4f4e65283cf
pref_challs = dns-01,
config_dir = /home/container/letsencrypt/config
work_dir = /home/container/letsencrypt/work
logs_dir = /home/container/logs
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
